export {default as Commodity} from './Commodity'
export {default as Home} from './Home'
export {default as NotFound} from './NotFound'
export {default as Setting} from './Setting'
export {default as Login} from './Login'

export {default as LoginLog} from './Home/LoginLog'
export {default as SystemHome} from './Home/SystemHome'
export {default as Hledit} from './Home/SystemHome/Hledit'
export {default as SystemInfo} from './Home/SystemInfo'
export {default as UserSetting} from './Home/UserSetting'
//设置的子路由
export {default as SetLoginLog} from './Setting/LoginLog'
export {default as SetSystemHome} from './Setting/SystemHome'
export {default as SetSystemInfo} from './Setting/SystemInfo'
export {default as SetUserSetting} from './Setting/UserSetting'
//商品子路由
export {default as CYProductList} from './Commodity/CYProductList'
export {default as CYAddProduct} from './Commodity/CYAddProduct'
export {default as CYProductDetail} from './Commodity/CYProductList/detail'
export {default as CYUserSetting} from './Commodity/CYUserSetting'